[package]
name = "rs_workdays"
version = "0.1.1"
authors = ["deepgreenAN <asami73dgreen63@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rs_workdays"
#crate-type = ["cdylib"]

[dependencies]
csv = "1.1"
chrono = "0.4"
lazy_static = "1.4.0"
numpy = "0.13"
ndarray = "0.14"



